### PR TITLE
NW4 - Gulnihal Naldoken - GitHub - Week 1

### PR DESCRIPTION
**Pull request by gulnihaln**
# Your Details

- Your Name: Gulnihal
- Your City: Manchester
- Your Slack Name: Gulnihal

# Homework Details

- Module:Github
- Week:1

### CODE REVIEW

**Comment by Anza-Azam** [comment]
Well done Gulnihal, brilliant job!

**Comment by gulnihaln** [comment]
> Well done Gulnihal, brilliant job!

Thanks Anza!

**Comment by Morteza-Khojasteh** [comment]
That's great!

**Comment by gulnihaln** [comment]
> That's great!

Thank you!

**Comment by omerffaruk** [comment]
Great job @gulnihaln

**Comment by gulnihaln** [comment]
> Great job @gulnihaln

Thanks Ömer!

**Comment by musayuksel** [comment]
Hi @gulnihaln  Great Job 👏
Just for information,
I think the title format will be different because in the .[template](https://github.com/CodeYourFuture/GitHomeworkFixErrors/commit/9d42aef6bc614418d7697904ab6f565160d02df8) there is info about title format like that,

> The title for your pull request should be made in this format
CITY CLASS_NO - FIRST_NAME LAST_NAME - MODULE - WEEK_NO
For example,
London Class 7 - Chris Owen - HTMl/CSS - Week 1

But I don't know is there any practical way🙈

**Review by zeinaji — COMMENTED** [review]
Great work 🙂

**Comment by gulnihaln** [comment]
> Great work 🙂

@zeinaji Thanks!

**Pull request closed without merging**
