### PR TITLE
West Midland 3-Nonye Ehiguese- Git and GitHub-Lesson 2

### PR DESCRIPTION
**Pull request by GemPearl**
Provided the correct answer to 18 Home work question with the help of a Calculator and google

# Your Details

- Your Name: Nonye Ehiguese
- Your City: West Midland
- Your Slack Name: Gempearl

# Homework Details

- Module: Git and Github
- Week: 2

-----
[View rendered homework.md](https://github.com/GemPearl/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by Professional-Kate** [comment]
Fantastic work, Nonye!  I have a couple of suggestions though... For question 5: you answered what CSS stands for but not what it is useful for, and for question 15: I would love to see that answer expanded and just for you to go into more detail! Really wonderful work though, amazing answers, although I would love to see those two areas expanded on.

**Comment by Johng117** [comment]
Good work Nonye, i like the way you use 'local' and 'remote' to explain the difference between your laptop/desktop and the web in your answers.

**Comment by GemPearl** [comment]
> Fantastic work, Nonye! I have a couple of suggestions though... For question 5: you answered what CSS stands for but not what it is useful for, and for question 15: I would love to see that answer expanded and just for you to go into more detail! Really wonderful work though, amazing answers, although I would love to see those two areas expanded on.

**Comment by GemPearl** [comment]
> Fantastic work, Nonye! I have a couple of suggestions though... For question 5: you answered what CSS stands for but not what it is useful for, and for question 15: I would love to see that answer expanded and just for you to go into more detail! Really wonderful work though, amazing answers, although I would love to see those two areas expanded on.

Many thanks Kate for the constructive feedback. It was helpful. Much appreciated. Feedback acted on.

**Comment by GemPearl** [comment]
> Good work Nonye, i like the way you use 'local' and 'remote' to explain the difference between your laptop/desktop and the web in your answers.

Thank you John for the review and feedback.

**Pull request closed without merging**
