### PR TITLE
West Midlands 3 - Kate Groutage - Git & GitHub - Week 1.

### PR DESCRIPTION
**Pull request by Professional-Kate**
Answered all the questions needed for Linus's homework.

# Your Details

- Your Name: Kate Groutage
- Your City: Birmingham
- Your Slack Name: Kate

# Homework Details

- Module: Git & GitHub
- Week: 1

-----
[View rendered homework.md](https://github.com/Professional-Kate/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by dotdashdon** [comment]
I am so glad I read this Kate. Really clear answers for the explanatory questions on Git/GitHub. Thank you. I was unable to find any errors!

**Comment by AstaRem** [comment]
Great answers Kate! By the way, I had the same issue in question 3 with * changing to _ when I save. 
If I may suggest, in question 17 - we record also WHY we made changes. 
Excellent work!
I have finished my review.

**Comment by Haseeb3927** [comment]
All answer are good & informative. Good effort Kate 💯

**Review by teejad — COMMENTED** [review]
I love how your answers are very informative! well done Kate!

**Pull request closed without merging**
