### PR TITLE
Nowak P. Help for kid

### PR DESCRIPTION
**Pull request by Pat-On**
written answers

# Your Details

- Your Name: Patryk Nowak
- Your City: Birmingham
- Your Slack Name: Patryk Nowak

# Homework Details

- Module: GIT
- Week: 1

### CODE REVIEW

**Review by scarabeo7 — COMMENTED** [review]
Good work Pat. It shows you know how to use github to fork, clone, push and do a pull request.

**Review by liewteh — CHANGES_REQUESTED** [review]
Overall well done, would suggest you review the answer for question 16 (line 101 - edited) with one of last week task https://classroom.google.com/c/MTU2NTIwNjUwNzgz/a/MTU3MTQ0NjkyODk2/details

**Review by scarabeo7 — APPROVED** [review]
Good work Pat. It shows you know how to use github to fork, clone, push and do a pull request.

**Comment by lish-dev** [comment]
Mr Nowak, the poor is probably in embarrassed by now :).  
Are you looking into changing your submission title as suggested in the pull request notes?

**Comment by Pat-On** [comment]
> Overall well done, would suggest you review the answer for question 16 (line 101 - edited) with one of last week task https://classroom.google.com/c/MTU2NTIwNjUwNzgz/a/MTU3MTQ0NjkyODk2/details

is it working?

**Pull request closed without merging**
