### PR TITLE
Birmingham Class 2 - Chizim Chinuru -  GitHomeworkFixErrors

### PR DESCRIPTION
**Pull request by scarabeo7**
Corrected wrong answers

### CODE REVIEW

**Review by liewteh — COMMENTED** [review]
Good job.
Did you miss question 17 accidentally?

**Comment by scarabeo7** [comment]
> Good job.
> Did you miss question 17 accidentally?

No I didn't. I added an answer to the one already provided as it's correct

**Review by cbaggini — APPROVED** [review]
Good job! No issues for me.

**Comment by liewteh** [comment]
> > Good job.
> > Did you miss question 17 accidentally?
> 
> No I didn't. I added an answer to the one already provided as it's correct.
> Also I did answer question 16 as Visual Studio Code. (VS Code) for short.

Thanks for your reply with regards to question 17. I did not comment on your question 16.

**Review by alsafi25 — COMMENTED** [review]
well done, I have finished my review

**Pull request closed without merging**
