### PR TITLE
London Class 7 - Tanika Robinson - Git and GitHub - Week 1

### PR DESCRIPTION
**Pull request by tanikaDev**
London Class 7 - Chris Owen - HTMl/CSS - Week 1

# Your Details

Tanika 
London
Tanika Robinson
# Homework Details

Git and GitHub
Week 1

### CODE REVIEW

**Comment by askinekincihf** [comment]
Great job Tanika! All of your answers are very descriptive, you definitely hit the ground running.

**Review by aishak05 — COMMENTED** [review]
Hi Tankika, great work! You have given some really good concise answers. My only suggestion would be for question 15 -  I would maybe elaborate to say commit will save a change you have made.

**Comment by Jpsi** [comment]
Great job!

**Comment by Jpsi** [comment]
Tip: In case you ever create a commit, and after that you realise that you may want to have added something more to it, you can try using the command `git commit --amend` from your terminal (I don't think this is available through GitHub Desktop). This will add your new (staged) changes to your last commit, and let you amend the commit name.

**Pull request closed without merging**
