### PR TITLE
North West Class 4 - Omer Yamak - Git & GitHub - Week 1 

### PR DESCRIPTION
**Pull request by omerffaruk**
Corrections and additions made for the answers where necessary.

# Your Details

- Your Name: Omer Yamak
- Your City: Manchester
- Your Slack Name: Omer

# Homework Details

- Module: Git & Github
- Week: 1

### CODE REVIEW

**Comment by Morteza-Khojasteh** [comment]
Well done

**Comment by omerffaruk** [comment]
> Well done

Thanks Morteza :)

**Comment by myaskylar** [comment]
Great job!

**Comment by omerffaruk** [comment]
> Perfectly corrected answers Omer! 👍

Thanks Haliema :)

**Pull request closed without merging**
