### PR TITLE
Ekrem's changes.

### PR DESCRIPTION
**Pull request by Ekremteke**
# Your Details

- Your Name: Ekrem
- Your City: Newcastle
- Your Slack Name: Ekrem Teke

# Homework Details

- Module: Github
- Week: First

-----
[View rendered homework.md](https://github.com/Ekremteke/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Review by Danti8686 — COMMENTED** [review]
Good answer Mr. Ekremteke 👍

**Comment by AnoshMalik** [comment]
All responses look good! 
I've finished the review

**Comment by levilu800b** [comment]
> # Your Details
> * Your Name: Ekrem
> * Your City: Newcastle
> * Your Slack Name: Ekrem Teke
> 
> # Homework Details
> * Module: Github
> * Week: First
> 
> [View rendered homework.md](https://github.com/Ekremteke/GitHomeworkFixErrors/blob/main/homework.md)

You did well with all questions answered.
Good Joob!

**Comment by Miguel-Cabral** [comment]
@Ekremteke  have a look again question number 1 am not sure 2 +2 =4 could you confirm again please?

**Comment by Ekremteke** [comment]
> # Question 5
> Could you add that "CSS helps with quicker style modifications of many website pages"?
> 
> Could you confirm the change?

Thank you @jo-joanna . You are right. I will use both definitions next time.

**Pull request closed without merging**
