### PR TITLE
Correcting and Updating Linus homework (Amanuel Tedros)

### PR DESCRIPTION
**Pull request by ATedy**
- Your Name: Amanuel Tedros
- Your City: Birmingham
- Your Slack Name: Amanuel

# Homework Details

- Module: Git/Github
- Week: 1

### CODE REVIEW

**Comment by hiqbal0121** [comment]
Looks good amanual, well done!

I have finished my review

**Comment by ATedy** [comment]
> Well done,Looks great to me.

Thank you! Peju.

**Comment by ATedy** [comment]
> Looks good Amanuel, well done!
> 
> I have finished my review

Much appreciated, thank you.

**Comment by ATedy** [comment]
> Looks good Amanuel, well done!
> 
> I have finished my review

Thank you

**Comment by ATedy** [comment]
> Looks good Amanuel, well done!
> 
> I have finished my review

Thank you, Haroon.

**Pull request closed without merging**
