### PR TITLE
Scotland Class 5 - Ivan Zhukov Git/GitHub - Week 2

### PR DESCRIPTION
**Pull request by zhkvivan**
# Your Details

- Your Name: Ivan Zhukov
- Your City: Glasgow
- Your Slack Name: Ivan Zhukov

# Homework Details

- Module: Intro Module Week 2 - Git & Github
- Week: 2

-----
[View rendered homework.md](https://github.com/zhkvivan/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by Andy-Robertson** [comment]
Hi Ivan,
I'm not sure your answer to question 11 is correct, can you check it?

Thanks,
Andy

**Comment by zhkvivan** [comment]
@Andy-Robertson oh right, I missed that question. Thank you.

**Comment by zhkvivan** [comment]
@Andy-Robertson Done.

**Comment by Andy-Robertson** [comment]
@zhkvivan Good job, looks much better!

**Comment by aalassv** [comment]
Hi Ivan, This is Isael,
Your job looks pretty neat.
Well done.

**Comment by zhkvivan** [comment]
Hi @aalassv Thank you!

**Pull request closed without merging**
