### PR TITLE
TheCheekyGithomework

### PR DESCRIPTION
**Pull request by TheCheekyGit**
# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

-----
[View rendered TheCheekyGithomework.md](https://github.com/TheCheekyGit/GitHomeworkFixErrors/blob/main/TheCheekyGithomework.md)

### CODE REVIEW

**Comment by Omer249a** [comment]
Hi Colette, check and edit Your Details

**Comment by Abadi11** [comment]
Hi Colette, I hope your'e are fine 

I am so sorry for bothering you. I want to finish last HW, I chose you :). 

I have two points 

1- The opposite of black is white (You have seemed hurry :) ).
2- In CSS, it is enough to type h1{} without #

I have finished my reviewer 

Thankyou :)

**Comment by TheCheekyGit** [comment]
Hahaha! Thank you!

**Comment by alastair87** [comment]
The answer to Question 6 is wrong (this is actually to do with CSS rather than git but it's important.

The correct answer is:

```css
h1 {

}
```

Type selectors such as `h1` or `p` are not preceded by any special characters in CSS.

**Comment by alastair87** [comment]
For Question 7, JavaScript is a programming language often used in both client-side and server-side web development (more on these later in the source). VS Code and Slack are also partly written in JavaScript, among other things.

Processing is one example of a library where the code is implemented using JavaScript but there are many others.

**Comment by alastair87** [comment]
Question 11:

Not quite - pull requests are a way of informing people what changes you'd like to merge in a branch. Often this is an upstream repository - a repository you've forked from but that you don't have permissions to change.

**Comment by alastair87** [comment]
Question 12:

The git history log details *all* the  history on the active branch, including that shared with other branches.

**Comment by alastair87** [comment]
Question 15:

When you 'commit your changes', you don't send your code to GitHub. All that happens is that git records the state of the repository at that point in time as a 'commit'. This is then a moment in time you can build from or revert to (or push to GitHub).

**Comment by alastair87** [comment]
Question 18:

You can also find help at losts of other places like StackOverflow. Sometimes just pasting an error message into your search engine (e.g. Google) can be a really good starting point.

**Comment by alastair87** [comment]
Question 5:

CSS is typically used for styling HTML documents and you can use it inside an html file with either the `style` tag or `style` attribute. However it is often good practice to put it in a separate file that your HTML file can then source with `<link href="style.css"></link>` where style.css is the path of the stylesheet.

**Comment by alastair87** [comment]
Excellent.

Next time you can just edit the original file unless the instructions tell you to create a new one. Git and GitHub record who the changes came from in the history. This also makes it easier to mark since comments can be added to specific lines in the file.

**Pull request closed without merging**
