### PR TITLE
correcting answers

### PR DESCRIPTION
**Pull request by Mohammedal-abdulhamid**
editing and changing the wrong answers

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

### CODE REVIEW

**Comment by niamhmadden23** [comment]
Hi @Mohammedal-abdulhamid , nice work correcting the answers!

**Comment by nax2uk** [comment]
Hi @Mohammedal-abdulhamid,
Thank you for completing your assignment 🙂
Your assignment is shown as missing on Google Classroom, even though you have done it on github. Can you submit your assignment on Google Classroom as well please? 

Thank you. 🙏🏽

**Comment by Mohammedal-abdulhamid** [comment]
> Hi @Mohammedal-abdulhamid,
> Thank you for completing your assignment 🙂
> Your assignment is shown as missing on Google Classroom, even though you have done it on github. Can you submit your assignment on Google Classroom as well please?
> 
> Thank you. 🙏🏽



> Hi @Mohammedal-abdulhamid,
> Thank you for completing your assignment 🙂
> Your assignment is shown as missing on Google Classroom, even though you have done it on github. Can you submit your assignment on Google Classroom as well please?
> 
> Thank you. 🙏🏽

Hi Azlina. thank you for feedback I'v submitted the link now sorry,

**Comment by Mohammedal-abdulhamid** [comment]
> Hi @Mohammedal-abdulhamid , nice work correcting the answers!

hi Niam

> Hi @Mohammedal-abdulhamid , nice work correcting the answers!

Hi @niamhmadden23 thank you for lovely feedback

**Pull request closed without merging**
