### PR TITLE
WestMidLands_Class 2- Fatimoh_Kuforiji - Git and GitHub- Week2

### PR DESCRIPTION
**Pull request by Fatimohkuforiji1**
# Your Details

- Your Name: Fatimoh Kuforiji
- Your City: Birmingham
- Your Slack Name: Fatimoh Kuforiji

# Homework Details

- Module: Git and GitHub
- Week: 2

### CODE REVIEW

**Review by nirmeet-baweja — COMMENTED** [review]
Hi Fatimoh! Great work. All your answers seem perfect. Well done. I just wanted to point out that you have added your codepen assignment in this pull request as well. But, it was meant to be added to another repository.

**Review by nirmeet-baweja — COMMENTED** [review]
I have finished my review.

**Comment by Fatimohkuforiji1** [comment]
@nirmeet-baweja , thank you so much for the observation. I will make the necessary correction.

**Comment by kwthr8** [comment]
Hello Fatimoh, good work, you got it all right. _(review by Kawthar)_

**Pull request closed without merging**
