### PR TITLE
Answer Questions

### PR DESCRIPTION
**Pull request by Morteza-Khojasteh**
help to Linus

# Your Details

- Your Name: Morteza Khojasteh
- Your City: Manchester
- Your Slack Name: Morteza khojasteh

# Homework Details

- Module: GitHub
- Week: 1

### CODE REVIEW

**Comment by gulnihaln** [comment]
Great job!

**Comment by omerffaruk** [comment]
Very well done Morteza 👍 You may consider adding more solutions to the "What three problem does Git & Github solve?" question since it is stated "three problems".

**Comment by Morteza-Khojasteh** [comment]
> Great job!

Thanks gulnihaln

**Comment by Morteza-Khojasteh** [comment]
> Very well done Morteza 👍 You may consider adding more solutions to the "What three problem does Git & Github solve?" question since it is stated "three problems".

Thanks for your attention Omer, I will revise it.

**Comment by myaskylar** [comment]
Great Job Moo!

**Comment by Morteza-Khojasteh** [comment]
> Great Job Moo!
Thanks Mya

**Comment by Morteza-Khojasteh** [comment]
> Good work Morteza.👍

Thanks, Abed

**Pull request closed without merging**
