### PR TITLE
WM3- Krishan Kumar Git/Github-Week 1

### PR DESCRIPTION
**Pull request by Krishan09**
Fixed Errors

# Your Details

- Your Name:  Krishan Kumar
- Your City:  Birmingham(West Midlands)
- Your Slack Name: Krishan Kumar

# Homework Details

- Module: Git & Github
- Week: 1

-----
[View rendered homework.md](https://github.com/Krrish-CYF/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by Halla-S** [comment]
I've finished my review .This is really good . You might have to change the title so others can recognise you easily .
 I did the same as you then changed it .

**Review by Halla-S — COMMENTED** [review]
I've finished my review .This is really good . You might need to change the title so others can recognise you easily .
I did the same as you then changed it .

**Comment by smkamaldar** [comment]
score 10/10 .you 've done it perfectly.

**Comment by MoTaKhi** [comment]
well done Krishan - Question 18 is already correct 
no need to change

**Pull request closed without merging**
