### PR TITLE
Homework answers updated

### PR DESCRIPTION
**Pull request by Know-Thyself**
# Your Details

- Your Name: Biruk Kebede
- Your City: West-midlands Class 2 
- Your Slack Name: Biruk

# Homework Details

- Module: Git 1
- Week: 2

### CODE REVIEW

**Review by scarabeo7 — APPROVED** [review]
Good work. It shows that you understand how to fork, clone, commit, push and do a pull request of a repo.

**Review by mikinet — CHANGES_REQUESTED** [review]
This is not a technical feedback,- it is evident you've accomplished the main task successfully- rather it is a theoretical one- a simple suggestion to review your answers (e.g. that of Q6). 
By the way, you are welcome to review my work and give me your feedback. Cheers.

**Comment by Know-Thyself** [comment]
Thanks @mikinet,
I appreciate your feedback! I will make the correction you suggested.
Cheers!

**Comment by Know-Thyself** [comment]
Thanks Chizim!
I appreciate your generous feedback!

**Pull request closed without merging**
