### PR TITLE
NW - Terry Calderbank - HomeworkFixErrors - Week 1

### PR DESCRIPTION
**Pull request by Texx45**
# Your Details

- Your Name: Terry Calderbank
- Your City: NW
- Your Slack Name: Terry

# Homework Details

- Module: Homework fix errors
- Week: 1

### CODE REVIEW

**Comment by Abed-Aghbar** [comment]
Hi Terry,
Good work, it is very good in my view.

**Comment by Ash-97** [comment]
Hi Terry, 
Everything looks perfect, well done.

**Comment by Salvacg737** [comment]
Hi Terry,

Your answers look fine and correct to me, good job!

**Review by SteveLeicester — COMMENTED** [review]
Good - thanks Terry

**Pull request closed without merging**
