### PR TITLE
West Midlands Class 2 - Cecilia Baggini - Git - 1

### PR DESCRIPTION
**Pull request by cbaggini**
# Your Details

- Your Name: Cecilia Baggini
- Your City: West Midlands
- Your Slack Name: Cecilia Baggini

# Homework Details

- Module: Git
- Week: 1

### CODE REVIEW

**Review by Pat-On — COMMENTED** [review]
For me everything ok.
Patryk N.

**Review by Pat-On — APPROVED** [review]

**Review by Pat-On — APPROVED** [review]

**Review by liewteh — CHANGES_REQUESTED** [review]
Nicely done.
Suggest review on the answer for question 7 (line 46 - edited), https://www.quora.com/What-programming-languages-are-web-browsers-like-Google-Chrome-Opera-and-Mozilla-Firefox-written-in

**Comment by cbaggini** [comment]
Thanks Liew, I think the way I expressed the answer wasn't clear. What I meant is that Javascript is the only language natively interpreted by most browsers, so I changed my answer. See here: https://www.quora.com/Why-is-JavaScript-the-only-client-side-language-available

**Review by Fatimohkuforiji1 — CHANGES_REQUESTED** [review]
Hello Celillia,

Well done on your work. Could you give  more explanation on what CSS is used for in a programming language?

Thank you.

**Pull request closed without merging**
