### PR TITLE
Glasgow Class 5 - Maarcis Ódónoñ - Git and Github - Week 1

### PR DESCRIPTION
**Pull request by MaarcisO**
Fixed the answers

# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

-----
[View rendered homework.md](https://github.com/MaarcisO/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by DJMF2015** [comment]
Looks great, Maaris. Only comment(s) is on question 6  i believe the answer is simply h1 { } to select all <h1> tags as oppose to #h1{ } which selects only class elements named h1. Otherwise great!

**Comment by DJMF2015** [comment]
Looks great, Maaris. Only comment(s) is on question 6  i believe the answer is simply h1 { } to select all <h1> tags as oppose to #h1{ } which selects only class elements named h1. Otherwise great!

**Comment by MaarcisO** [comment]
> Looks great, Maaris. Only comment(s) is on question 6 i believe the answer is simply 'h1 { }' to select all '
> 
> # ' tags as oppose to '#h1{ }' which selects only class elements named h1. Otherwise great!'

Thank you! I have now fixed that answer :)

**Review by socrateskld — COMMENTED** [review]
Nice job Maarcis

**Pull request closed without merging**
