### PR TITLE
fixed the errors in the linus's homework-Correct answers

### PR DESCRIPTION
**Pull request by konikalily**
# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

### CODE REVIEW

**Comment by konikalily** [comment]
Provided correct answers..
Konika Biswas
Leeds

**Comment by konikalily** [comment]
> # Your Details
> * Your Name: Konika Biswas
> * Your City: Leeds
> * Your Slack Name: Konika Biswas
> 
> # Homework Details
> * Module: GitHomeworkFixErrors
> * Week:Week 2

**Comment by konikalily** [comment]
> Hi Konika, can't find any wrong with your answers, and nice description in each of your answers 🙂

Thank you Haliema. 👍

**Comment by gulnihaln** [comment]
Hi @konikalily,

Great job! 
There is template that shows how to write the title for this homework. You'll see it in VS code. You can edit the title from here. I also haven't seen it.

**Pull request closed without merging**
