### PR TITLE
WM3 - Wiam_Nasr - Git/Github - Week 1

### PR DESCRIPTION
**Pull request by wiamnasr**
# Your Details

- Your Name: Wiam Nasr
- Your City: Birmingham
- Your Slack Name: Wiam Nasr

# Homework Details

- Module: Git/Github
- Week: 1

-----
[View rendered homework.md](https://github.com/wiamnasr/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by TomRafferty** [comment]
Great work! I think 'Version Control' should be added to the "what problems does git solve" but honestly, nice answers with lots of detail :D

**Comment by AstaRem** [comment]
Great work Wiam! My only suggestion for question 17 - as I understand it wants us to describe, what for is the message field (not the commit button itself).
Excellent work!
I have finished my review.

**Comment by wiamnasr** [comment]
Thank you, I have went ahead and amended what you suggested

**Comment by itsrahmaa** [comment]
love your detailed answers, well done Wiam 👍

**Pull request closed without merging**
