### PR TITLE
Scotland Class 5 - Ben Ojika - HTML/CSS - Week 6

### PR DESCRIPTION
**Pull request by ojikaemeka**
Home work was worked on and corrected.

# Your Details

- Your Name: Ben Ojika
- Your City: Glasgow
- Your Slack Name: Ben

# Homework Details

- Module: GitHub
- Week: 6

-----
[View rendered homework.md](https://github.com/ojikaemeka/GitHomeworkFixErrors/blob/main/homework.md)

### CODE REVIEW

**Comment by Tara-Q** [comment]
Looks great Ben, except you might want to check Q6 again ;)

**Comment by ojikaemeka** [comment]
> Looks great Ben, except you might want to check Q6 again ;)

Thank you. The correction has been implemented.

**Comment by Tara-Q** [comment]
Nice one. My review has been completed.

**Comment by socrateskld** [comment]
Good work Ben

**Comment by ku562** [comment]
Good work Ben.

**Pull request closed without merging**
