### PR TITLE
West Midlands Class 2 - Jasvir Kaur - Git/Github - Week 2

### PR DESCRIPTION
**Pull request by JK1320**
# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

### CODE REVIEW

**Comment by mame-baba** [comment]
Hi Jas, i have checked all your answers and they seem to be all fine. However on question10 i cannot really see the answers maybe it is due to the format. could you please confirm. 
Many Thanks
Well done.

**Comment by moniqueking57** [comment]
Hi Jasvir, 

It looks great well done :)

**Comment by JK1320** [comment]
> Hi Jas, i have checked all your answers and they seem to be all fine. However on question10 i cannot really see the answers maybe it is due to the format. could you please confirm.
> Many Thanks
> Well done.

Hi Mame,
Thanks for the comment. I have checked the answer for question 10 and I can see it.

**Comment by samia-pk** [comment]
Hi Jas 
Here i was looking for others homework for feedback. but you done it already. can you please check my work for this assignment. 
Thanks.

**Comment by JK1320** [comment]
> Hi Jas
> Here i was looking for others homework for feedback. but you done it already. can you please check my work for this assignment.
> Thanks.

Hi Samia, you can still review my work so that you know how to review.
I have done yours now.

**Comment by samia-pk** [comment]
> Hi Jasvir,
> 
> It looks great well done :)



> > Hi Jas
> > Here i was looking for others homework for feedback. but you done it already. can you please check my work for this assignment.
> > Thanks.
> 
> Hi Samia, you can still review my work so that you know how to review.
> I have done yours now.

@JK1320 yeah i review your work. & learn many things, i can make corrections now :D

**Pull request closed without merging**
