### PR TITLE
NorthWest Class 4 - Anza Azam - Github - Week 1

### PR DESCRIPTION
**Pull request by Anza-Azam**
# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

### CODE REVIEW

**Comment by Morteza-Khojasteh** [comment]
Anza check line 17, I think when you save your file in VS code it has happened

**Comment by gulnihaln** [comment]
Anza,
I liked your answer for the last question very much :) I agree with Morteza, there is a mistake on the line 17.  Great correction!

**Comment by Anza-Azam** [comment]
> Anza check line 17, I think when you save your file in VS code it has happened

Thank you, I'll go and check, yes VS Code issue do you know how to fix it, if yes please let me know.

**Comment by Anza-Azam** [comment]
> Anza,
> I liked your answer for the last question very much :) I agree with Morteza, there is a mistake on the line 17. Great correction!

Thank you Gulnihal, I'll try to fix it soon.

**Pull request closed without merging**
